### PR TITLE
chore: update packages

### PR DESCRIPTION
**Pull request by dated**
Updates packages and babel config.

## What kind of change does this PR introduce?

- [ ] Bugfix
- [ ] Feature
- [ ] Refactor
- [ ] Performance
- [ ] Tests
- [x] Build
- [ ] Documentation
- [ ] Code style update
- [ ] Continuous Integration
- [ ] Other, please describe:

## Does this PR introduce a breaking change?

- [ ] Yes
- [x] No

## Does this PR release a new version?

- [ ] Yes
- [x] No

If yes, please describe the impact and migration path for existing applications:

**The PR fulfills these requirements:**

- [ ] It's submitted to the `develop` branch, _not_ the `master` branch
- [ ] All tests are passing
- [ ] New/updated tests are included

If adding a **new feature**, the PR's description includes:

- [ ] A convincing reason for adding this feature (to avoid wasting your time, it's best to open a suggestion issue first and wait for approval before working on it)

### CODE REVIEW

**Comment by faustbrian** [comment]
@dated could you run ncu again since this has been opened almost 4 weeks ago.

**Comment by dated** [comment]
I'll do that asap.

**Comment by alexbarnsley** [comment]
I didn't even see this

**Comment by dated** [comment]
:susp:

**Comment by dated** [comment]
@faustbrian done as asked

**Pull request merged**
